name: 'DBT_SETUP'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'DBT_SETUP'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  DBT_SETUP:
    example:
      +materialized: table
